{{- if (not .Values.pgadmin.existingPasswordSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgadmin.passwordSecret" . }}
  labels:
    app: {{ template "pgadmin.fullname" . }}
    chart: {{ template "pgadmin.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  pgadmin-password: {{ default "admin" .Values.pgadmin.password | b64enc | quote }}
{{- end }}
---
{{- if .Values.pgadmin.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgadmin.fullname" . }}-tls
  labels:
    app: {{ template "pgadmin.fullname" . }}
    chart: {{ template "pgadmin.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  server.cert: {{ .Files.Get "certs/server.cert" | b64enc }}
  server.key: {{ .Files.Get "certs/server.key" | b64enc }}
{{- end }}
