apiVersion: v1
kind: Service
metadata:
  name: {{ template "pgadmin.fullname" . }}
  labels:
    app: {{ template "pgadmin.name" . }}
    chart: {{ template "pgadmin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ with .Values.service.loadBalancerSourceRanges }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
   {{- if .Values.pgadmin.tls }}
    - port: {{ .Values.service.tlsport }}
      targetPort: https
      protocol: TCP
      name: https
   {{- end }}
  selector:
    app: {{ template "pgadmin.name" . }}
    release: {{ .Release.Name }}
